name: Main

on:
  push:
    branches: [main]
  pull_request:

jobs:
   validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: mkdir -p .tmp && curl -sSL 'https://json.schemastore.org/github-action.json' > .tmp/github-action.json
      - uses: thiagodnf/yaml-schema-checker@v0.0.12
        with:
          jsonSchemaFile: .tmp/github-action.json
          yamlFiles: |
            */action.yml
